azs:
- name: z1
  cloud_properties: {availability_zone: AVAILABILITY_ZONE}

vm_types:
- name: default
  cloud_properties:
    instance_type: m3.medium
    ephemeral_disk:
      size: 10240
      type: gp2

disk_types:
- name: default
  disk_size: 1024
  cloud_properties:
    type: gp2

networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.0.0/20
    gateway: 10.0.0.1
    dns:
    - 10.0.0.2
    az: z1
    reserved:
    - 10.0.0.2 - 10.0.0.9
    cloud_properties:
      security_groups:
      - SECURITY_GROUP
      subnet: SUBNET_ID

compilation:
  workers: 3
  reuse_compilation_vms: true
  az: z1
  vm_type: compilation
  network: default
