name: "performance"
director_uuid: DIRECTOR_UUID

releases:
- name: routing-perf
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: gostatic
  instances: 1
  vm_type: default
  stemcell: trusty
  azs: [z1]
  jobs:
  - name: gostatic
    release: routing-perf
    provides:
      static: {as: gostatic}
    properties:
      gostatic:
        response_size: 1
  networks:
  - name: default

- name: http_route_populator
  instances: 1
  vm_type: default
  stemcell: trusty
  azs: [z1]
  jobs:
  - name: http_route_populator
    release: routing-perf
    consumes:
      static: {from: gostatic}
    properties:
      http_route_populator:
        nats: http://NATS_USER:NATS_PASSWORD@NATS_ENDPOINT:NATS_PORT
        app_domain: foo.com
        app_name: gostatic
        num_routes: 100000
  networks:
  - name: default

- name: tcp_route_populator
  instances: 1
  vm_type: default
  stemcell: trusty
  azs: [z1]
  jobs:
  - name: tcp_route_populator
    release: routing-perf
    consumes:
      static: {from: gostatic}
    properties:
      tcp_route_populator:
        routing_api_url: http://ROUTING_API_URL:ROUTING_API_PORT
        external_port_start: 60000
        external_port_end: 60999
        sleep_interval: 10
  networks:
  - name: default

- name: http_performance_tests
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: trusty
  azs:
  - z1
  networks:
  - name: default
  jobs:
  - name: performance_tests
    release: routing-perf
    properties:
      performance_tests:
        routers:
          - address: GOROUTER_API_ADDRESS
            tag: gorouter
        host: gostatic-0.foo.com
        port: 80
        protocol: http
        num_requests: 50000
        concurrent_requests: 2
        datadog_api_key: DATADOG_API_KEY
        throughput_lower_limit: 1000
        latency_upper_limit_90: 8
        latency_upper_limit_95: 10
        latency_upper_limit_99: 11

- name: tcp_performance_tests
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: trusty
  azs:
  - z1
  networks:
  - name: default
  jobs:
  - name: performance_tests
    release: routing-perf
    properties:
      performance_tests:
        routers:
          - address: TCP_ROUTER_API_ADDRESS
            tag: tcp_router
        host: tcp.bosh-lite.com
        port: 60001
        protocol: http
        num_requests: 50000
        concurrent_requests: 2
        datadog_api_key: DATADOG_API_KEY
        throughput_lower_limit: 3200
        latency_upper_limit_90: 8
        latency_upper_limit_95: 10
        latency_upper_limit_99: 11

update:
  canaries: 1
  canary_watch_time: 5000-120000
  max_in_flight: 1
  serial: false
  update_watch_time: 5000-120000
